### ISSUE TITLE
[问题]  /etc/init.d/celeryd start 执行报错

### ISSUE THREAD

**Issue by jefffffffffffffffff** [pythonzm/Ops#20]
按照文档执行,etc/init.d/celeryd start 报错,报错如下:

```
ops) [root@ops-common-python-person-1eiqn3l-5788 Ops]# /etc/init.d/celeryd start
celery init v10.1.
Using config script: /etc/default/celeryd
celery multi v4.2.0 (windowlicker)
> Starting nodes...
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/__main__.py", line 20, in <module>
    main()
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/root/.pyenv/versions/3.6.6/envs/ops/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Ops'
	> worker@ops-common-python-person-1eiqn3l-5788.novalocal: * Child terminated with exit code 1
FAILED
```

##如果出现celeryd无法启动，则添加环境变量：export C_FORCE_ROOT="true", 已按照此方法处理,仍然报错.

**Comment by pythonzm** [comment]
celery的配置文件按照自己的环境修改了么？

**Comment by jefffffffffffffffff** [comment]
@pythonzm 麻烦提供下具体要改哪些东西,谢谢.

**Comment by motume** [comment]
[root@localhost Ops]# /etc/init.d/celeryd start
celery init v10.1.
Using config script: /etc/default/celeryd
bash: /app/.pyenv/versions/test-3.6/bin/celery: No such file or directory
我有个这个....不知道是啥意思, 找不到这个文件?

**Comment by grayflight** [comment]
最后怎么解决的？我也遇到了类似的错误
